# Generated by Django 2.2.6 on 2019-11-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20191109_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='book',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='lar_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures_large'),
        ),
        migrations.AddField(
            model_name='book',
            name='sm_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures_small'),
        ),
        migrations.AddField(
            model_name='book',
            name='subdes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
