# Generated by Django 2.2.6 on 2019-12-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='cover'),
        ),
        migrations.AddField(
            model_name='book',
            name='firstpage',
            field=models.TextField(null=True),
        ),
    ]
